### ISSUE TITLE
Problem with the transparency of an image

### ISSUE THREAD

**Issue by josepsanzcamp** [code-lts/WarnockPDF#10]
Hi.

I have detected a problem with the alpha channel embedded on the image, you can see the problem with the example_042.php.

Thanks in advance.

Josep.

**Comment by josepsanzcamp** [comment]
Hi William.

I have found the problem: in line 7025 of the src/WarnockPDF.php, the first argument passed to the method_exists must contains the namespace of the Images class, if you replace 'Images' by '\WarnockPDF\Images' the problem will be solved.

Josep.

**Comment by mvorisek** [comment]
Please submit PR into https://github.com/tecnickcom/TCPDF lib

**Comment by williamdes** [comment]
> Hi William.
> 
> I have found the problem: in line 7025 of the src/WarnockPDF.php, the first argument passed to the method_exists must contains the namespace of the Images class, if you replace 'Images' by '\WarnockPDF\Images' the problem will be solved.
> 
> Josep.

Hi @josepsanzcamp 
Thank you for finding this issue, could you please confirm it only exists on the WarnockPDF repo ?

**Comment by josepsanzcamp** [comment]
> Please submit PR into https://github.com/tecnickcom/TCPDF lib

Hi Michael.

This bug only be present in WarnockPDF, not in TCPDF, was caused by the code reorganization.

Josep.

**Comment by josepsanzcamp** [comment]
> > Hi William.
> > I have found the problem: in line 7025 of the src/WarnockPDF.php, the first argument passed to the method_exists must contains the namespace of the Images class, if you replace 'Images' by '\WarnockPDF\Images' the problem will be solved.
> > Josep.
> 
> Hi @josepsanzcamp
> Thank you for finding this issue, could you please confirm it only exists on the WarnockPDF repo ?

Hi William.

The problem only is present in WarnockPDF because is caused by your code reorganization.

Josep.
